### ISSUE TITLE
Config option: reveal curse information conditionally

### ISSUE THREAD

**Issue by FewerFlaws** [zabi94/CurseSilence#4]
I like the idea of hiding/obscuring curses, but it doesn't seem right to continue hiding that information once the nature of the curse is known.  As a config option, this mod should reveal the full tooltip once the curse has activated once or twice.  Revealing the full tooltip when equipping the cursed item is another decent behaviour.

With the options I described this mod would go very well with others that add new curses and cursed items.

**Comment by zabi94** [comment]
This unfortunately is unachievable, since both item data (to store the "isRevealed" piece of info) and curse activation logic are server side, and this is client only

**Comment by FewerFlaws** [comment]
Hmm, I bet you could store data in a config file to keep track of items by their type and nbt signature.  That would mean that revealing the curse information on one pair of diamond boots with Feather Fall II and Curse of Pain I would reveal the curse on every copy of that item.  One could argue that the character learns more about curses in general every time he encounters one.

Though choosing when to modify the config file does seem tricky.  If the server handles all of the curse logic then sends clients the effects then there's ambiguity in where exactly the effect comes from.  It might work to watch for the anticipated effect based on type and duration/magnitude, but that does seem clunky.

Sounds like it's out of the scope of the mod.  Thank you for the response =]

**Comment by zabi94** [comment]
Storing data in an external structure would be extremely dirty too, there is no proper itemstack lifecycle where i could decide to drop data for an item once it gets destroyed or despawns. 

The file would grow without limits, making it longer and longer to parse and search data in. 

Every time a new curse is placed on an item i would have to add one or more entries to the file.

I could make it a client-server mod to do that directly on the item data, but i'd rather not honestly.

**Comment by FewerFlaws** [comment]
Yep, I understand and agree.  The functionality is best accomplished with a client-server mod ^_^
